config/routes.rb
Rails.application.routes.draw do


  root "students#index"

  #get "/students", to: "students#index"
  #get "/students/:id", to: "students#show"

  resources :students do
  	resources :comments
  end
  
  resources :book 
  

  resources :author 
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/account.rb
class Account < ApplicationRecord
    belongs_to :supplier
    has_one :account_history
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :physician
  belongs_to :paitient
end

app/models/assembly.rb
class Assembly < ApplicationRecord
    has_and_belongs_to_many :parts
end

app/models/author.rb
class Author < ApplicationRecord
   has_many :books
   validates_associated :books
end

app/models/book.rb
class Book < ApplicationRecord
    belongs_to :author 
end

app/models/car.rb
class Car < Vehicle
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :student
end

app/models/employee.rb
class Employee < ApplicationRecord
    has_many :subordinates, class_name: "Employee",
    foreign_key: "manager_id"

    belongs_to :manager, class_name: "Employee", optional: true
end

app/models/new_model.rb
class NewModel < ApplicationRecord
    has_many :pictures, as: :imageable
end

app/models/paitient.rb
class Paitient < ApplicationRecord
  has_many :appointments
  has_many :physicians, through: :appointments
end

app/models/part.rb
class Part < ApplicationRecord
    has_and_belongs_to_many :assemblies
end

app/models/person.rb
class Person < ApplicationRecord
    validates :name, presence: true
    validates :terms_of_service, acceptance: { accept: 'yes' }
end

app/models/physician.rb
class Physician < ApplicationRecord
  has_many :appointments
  has_many :paitients, through: :appointments
end

app/models/picture.rb
class Picture < ApplicationRecord
    belongs_to :imageable, polymorphic: true
end

app/models/product.rb
class Product < ApplicationRecord
    has_many :pictures, as: :imageable 
end

app/models/student.rb
class Student < ApplicationRecord
	has_many :comments

	validates :first_name, presence: true
	validates :last_name, presence: true
    validates :class_name, presence: true, length: {minimum:1 ,maximum: 10 }
end

app/models/supplier.rb
class Supplier < ApplicationRecord
    has_one :account
    has_one :account_history, through: :account
end

app/models/todo.rb
class Todo < ApplicationRecord
    belongs_to :user, primary_key: 'guid'
end

app/models/user.rb
class User < ApplicationRecord
    self.primary_key = 'guid'
end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
end

app/models/writer.rb
class Writer < ApplicationRecord
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def index
  	@student = Student.all
  end

  def show
    @student = Student.find(params[:id])
  end
  
  def new
  	@student = Student.new

  end
  
  def create

  	@student = Student.new(student_params)

  	if @student.save
        redirect_to @student
    else
        render :new, status: :unprocessable_entity
    end
  end

  def edit
  	@student = Student.find(params[:id])
  end

  def update
    @student = Student.find(params[:id])

    if @student.update(student_params)
      redirect_to @student
    else
      render :edit, status: :unprocessable_entity
    end
  end 

  def destroy

  	@student = Student.find(params[:id])
  	@student.destroy

    redirect_to @student, status: :see_other
  end

  private

  def student_params
  	params.require(:student).permit(:first_name, :last_name, :class_name)
  end

end

app/helpers/student_helper.rb
module StudentHelper
end

app/views/students/edit.html.erb
<h1>Edit Article</h1>

<%= form_with model: @student do |form| %>
  <div>
    <%= form.label :FirstName %><br>
    <%= form.text_field :first_name %>
  </div>

  <div>
    <%= form.label :LastName %><br>
    <%= form.text_field :last_name %>
  </div>
  
  <div>
    <%= form.label :Class %><br>
    <%= form.text_field :class_name %>
  </div>
  <br/>
  <div>
    <%= form.submit %>
  </div>

<% end %>

app/views/students/index.html.erb
<h1>Student Data</h1>

<table>
	<tr>
		<th>First Name</th>
		<th>Last Name</th>
		<th>Class</th>
		<th>Show Link</th>
		<th>Delete</th>
		<th>Comments</th>
	</tr>


		<% @student.each do |s| %>
		 
			<tr>
				
				<td><%= s.first_name %></td>
				<td><%= s.last_name %></td>
				<td><%= s.class_name %></td>
				<td>
				  <a href="<%= student_path(s) %>">Student Details </a>
				</td>
				<td>
					<%= link_to "Destroy", student_path(s.id), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                     } %>
                </td>
			</tr>
		<% end %>
		<tr>
			<button><a href="<%= new_student_path %>">New Student</a></button>
		</tr>   
   <tr>

</table>

app/views/students/new.html.erb
<h1>New Article</h1>

<%= form_with model: @student do |form| %>
  <div>
    <%= form.label :FirstName %><br>
    <%= form.text_field :first_name %>
    <% @student.errors.full_messages_for(:first_name).each do |message| %>
    <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :LastName %><br>
    <%= form.text_area :last_name %>
  </div>
  
  <div>
    <%= form.label :Class %><br>
    <%= form.text_field :class_name %>
     <% @student.errors.full_messages_for(:class_name).each do |message| %>
     <div><%= message %></div>
    <% end %>
  </div>
  
  <div>
    <%= form.submit %>
  </div>

<% end %>

app/views/students/show.html.erb
<h1>Student</h1>
<table>
	
			<tr>
				<th>First Name: -</th>
				<td><%= @student.first_name %></td>
			</tr>
			<tr>
				<th>Last Name: -</th>
				<td><%= @student.last_name %></td>
			</tr>
			<tr>
				<th>Class: -</th>
				<td><%= @student.class_name %></td>
			</tr>
			<tr>
				
				<td><a href="<%= students_path %>">Previous</a></td>
				<td><a href="<%= edit_student_path(@student) %>">Edit</a></td>
	
			</tr>
			</tr>			
</table>
<h2>Comments</h2>
<% @student.comments.each do |comment| %>
  <p>
    <strong>Commenter:</strong>
    <%= comment.commenter %>
  </p>

  <p>
    <strong>Comment:</strong>
    <%= comment.body %>
  </p>
<% end %>

<h2>Add a Comment:</h2>

<%= form_with model: [ @student, @student.comments.build ] do |form| %>
  <p>
    <%= form.label :commenter %><br>
    <%= form.text_field :commenter %>
  </p>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>